#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-/public/home/yanhongru/ICLR2027/Reflex}"
cd "${ROOT}"

export SOURCE_H5_PATH="${SOURCE_H5_PATH:-${ROOT}/experiments/maniskill/data/fix3_733/canonical_h5/peg_disturb_seed1051032_idx0008.fix3/peg_disturb_seed1051032_idx0008.h5}"
export SOURCE_KEY="${SOURCE_KEY:-peg_disturb_seed1051032_idx0008}"
export REQUIRE_SOURCE_H5_PROTOCOL="${REQUIRE_SOURCE_H5_PROTOCOL:-true}"
export SOURCE_H5_PEG_PERTURB_MODE="${SOURCE_H5_PEG_PERTURB_MODE:-force}"
export SOURCE_H5_PEG_FORCE_SCALE="${SOURCE_H5_PEG_FORCE_SCALE:-25.0}"
export SOURCE_H5_PEG_FORCE_STEPS="${SOURCE_H5_PEG_FORCE_STEPS:-8}"
export RUN_GROUP="${RUN_GROUP:-peg_disturb}"
export SCENARIO_NAME="${SCENARIO_NAME:-source_peg_disturb_seed1051032_idx0008}"
export MAX_EPISODE_STEPS="${MAX_EPISODE_STEPS:-420}"
export NEAR_TARGET_L2="${NEAR_TARGET_L2:-0.16}"
export MAX_FINISHER_STEPS="${MAX_FINISHER_STEPS:-180}"
export FINISHER_CONTROLLER="${FINISHER_CONTROLLER:-diffusion_policy}"
export MAX_PREMOTION_COSMOS_PREDICTIONS="${MAX_PREMOTION_COSMOS_PREDICTIONS:-4}"
export MIN_COSMOS_DYNAMIC_ACTIONS_BEFORE_FINISHER="${MIN_COSMOS_DYNAMIC_ACTIONS_BEFORE_FINISHER:-4}"
export PIPELINE_TIMEOUT="${PIPELINE_TIMEOUT:-20m}"
export COSMOS_BUILD_TIMEOUT_S="${COSMOS_BUILD_TIMEOUT_S:-180}"
export COSMOS_INFERENCE_TIMEOUT_S="${COSMOS_INFERENCE_TIMEOUT_S:-900}"
export COSMOS_EXTRACT_TIMEOUT_S="${COSMOS_EXTRACT_TIMEOUT_S:-180}"

bash scripts/slurm/run_phase03_oracle_full_pipeline_in_allocation.sh
