#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-/public/home/yanhongru/ICLR2027/Reflex}"
cd "${ROOT}"

export RUN_GROUP=render_probe
export RUN_NAME="${RUN_NAME:-fast06f}"
export RENDER_SHADER_PACK="${RENDER_SHADER_PACK:-minimal}"
export RENDER_CANARY_API="${RENDER_CANARY_API:-gym}"
export RENDER_PROBE_TIMEOUT="${RENDER_PROBE_TIMEOUT:-90s}"

export FULL_RUN_GROUP=h5_fastshift
export FULL_RUN_NAME="${FULL_RUN_NAME:-try06}"
export FULL_RUN_SCRIPT=scripts/slurm/phase03_h5_source.sh

export SOURCE_KEY="${SOURCE_KEY:-hole_late_fast_shift_seed10300253_idx5010}"
export REQUIRE_TARGET_MOTION_COMPLETE_BEFORE_FINISHER="${REQUIRE_TARGET_MOTION_COMPLETE_BEFORE_FINISHER:-true}"
export MAX_COSMOS_ROUNDS="${MAX_COSMOS_ROUNDS:-6}"
export MAX_PREMOTION_COSMOS_PREDICTIONS="${MAX_PREMOTION_COSMOS_PREDICTIONS:-4}"
export COSMOS_ACTION_HORIZON="${COSMOS_ACTION_HORIZON:-8}"
export MIN_COSMOS_DYNAMIC_ACTIONS_BEFORE_FINISHER="${MIN_COSMOS_DYNAMIC_ACTIONS_BEFORE_FINISHER:-4}"
export FINISHER_CONTROLLER="${FINISHER_CONTROLLER:-diffusion_policy}"
export DYNAMIC_CONTROLLER="${DYNAMIC_CONTROLLER:-cosmos3_policy}"
export MAX_FINISHER_STEPS="${MAX_FINISHER_STEPS:-520}"
export MAX_EPISODE_STEPS="${MAX_EPISODE_STEPS:-650}"
export NEAR_TARGET_L2="${NEAR_TARGET_L2:-0.16}"
export PIPELINE_TIMEOUT="${PIPELINE_TIMEOUT:-90m}"

bash scripts/slurm/phase03_render_gpu_probe.sh
